version: '3.9'
services:
  db:
    image: mysql:8.0.31
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
    volumes:
      - ./scripts/schema.sql:/docker-entrypoint-initdb.d/schema.sql
  adopet:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: adopet
    ports:
      - '8080:8080'
    environment:
      - ADDITIONAL_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xmx1G -Xms128m -XX:MaxMetaspaceSize=128m
      - PROFILE=dev
    links:
      - db
    depends_on:
      - db